import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { AlertTriangle, AlertCircle, PhoneCall, FileText, ShieldAlert } from "lucide-react"

export default function Disclaimer() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1 py-12 px-4 bg-gray-50">
        <div className="container mx-auto max-w-4xl">
          <div className="text-center mb-12">
            <h1 className="text-3xl md:text-4xl font-bold mb-4">Medical Disclaimer</h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Important information about the limitations of our AI medical chatbot
            </p>
            <p className="text-gray-500 mt-2">Last Updated: March 11, 2025</p>
          </div>

          <Alert variant="destructive" className="mb-8">
            <AlertTriangle className="h-5 w-5" />
            <AlertTitle className="text-lg font-bold">Important Notice</AlertTitle>
            <AlertDescription>
              MediChat is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the
              advice of your physician or other qualified health provider with any questions you may have regarding a
              medical condition.
            </AlertDescription>
          </Alert>

          <Card className="mb-8">
            <CardHeader className="flex flex-row items-center gap-4 pb-2">
              <AlertCircle className="h-8 w-8 text-primary" />
              <CardTitle className="text-2xl">General Disclaimer</CardTitle>
            </CardHeader>
            <CardContent className="pt-4">
              <p className="text-gray-700 mb-4">
                MediChat is an AI-powered chatbot designed for informational purposes only. The information provided by
                MediChat is not intended to be a substitute for professional medical advice, diagnosis, or treatment.
              </p>
              <p className="text-gray-700 mb-4">
                The content provided by MediChat is generated by artificial intelligence based on general medical
                knowledge and may not account for your specific health situation, medical history, or individual needs.
              </p>
              <p className="text-gray-700">
                While we strive to provide accurate and up-to-date information, we make no representations or warranties
                of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or
                availability of the information, products, services, or related graphics contained within MediChat for
                any purpose.
              </p>
            </CardContent>
          </Card>

          <Card className="mb-8">
            <CardHeader className="flex flex-row items-center gap-4 pb-2">
              <FileText className="h-8 w-8 text-primary" />
              <CardTitle className="text-2xl">Consult a Professional</CardTitle>
            </CardHeader>
            <CardContent className="pt-4">
              <p className="text-gray-700 mb-4">
                Always seek the advice of your physician or other qualified health provider with any questions you may
                have regarding a medical condition. Never disregard professional medical advice or delay in seeking it
                because of something you have read or received from MediChat.
              </p>
              <p className="text-gray-700 mb-4">Healthcare professionals should be consulted for:</p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Diagnosis of medical conditions</li>
                <li>Treatment recommendations and medication advice</li>
                <li>Interpretation of test results</li>
                <li>Personalized health guidance based on your medical history</li>
                <li>Any persistent, severe, or concerning symptoms</li>
              </ul>
              <p className="text-gray-700 mt-4">
                MediChat may suggest when it's appropriate to seek professional medical care, but these suggestions are
                not a replacement for professional judgment.
              </p>
            </CardContent>
          </Card>

          <Card className="mb-8">
            <CardHeader className="flex flex-row items-center gap-4 pb-2">
              <ShieldAlert className="h-8 w-8 text-primary" />
              <CardTitle className="text-2xl">No Doctor-Patient Relationship</CardTitle>
            </CardHeader>
            <CardContent className="pt-4">
              <p className="text-gray-700 mb-4">
                Using MediChat does not create a doctor-patient relationship between you and MediChat, its creators,
                operators, or any affiliated healthcare professionals.
              </p>
              <p className="text-gray-700 mb-4">
                The information provided by MediChat is general in nature and is not tailored to your specific health
                needs or medical history in the way that advice from your doctor would be.
              </p>
              <p className="text-gray-700">
                MediChat does not have access to your complete medical records, cannot perform physical examinations,
                and cannot order or interpret diagnostic tests.
              </p>
            </CardContent>
          </Card>

          <Card className="mb-8">
            <CardHeader className="flex flex-row items-center gap-4 pb-2">
              <PhoneCall className="h-8 w-8 text-primary" />
              <CardTitle className="text-2xl">Emergency Disclaimer</CardTitle>
            </CardHeader>
            <CardContent className="pt-4">
              <div className="bg-red-50 border border-red-200 rounded-md p-4 mb-4">
                <p className="text-red-800 font-bold">
                  If you are experiencing a medical emergency, call your local emergency services immediately (such as
                  911 in the United States) or go to the nearest emergency room or urgent care center.
                </p>
              </div>
              <p className="text-gray-700 mb-4">
                MediChat is not designed to handle emergency situations and should not be used in emergency
                circumstances, including but not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Chest pain or difficulty breathing</li>
                <li>Severe bleeding or traumatic injury</li>
                <li>Sudden severe headache or loss of consciousness</li>
                <li>Sudden confusion, trouble speaking, or understanding speech</li>
                <li>Sudden weakness or numbness, especially on one side of the body</li>
                <li>Severe allergic reactions</li>
                <li>Suicidal thoughts or intentions</li>
              </ul>
              <p className="text-gray-700 mt-4">
                Delay in seeking proper medical care could result in serious injury or death.
              </p>
            </CardContent>
          </Card>

          <Card className="mb-8">
            <CardHeader className="flex flex-row items-center gap-4 pb-2">
              <AlertTriangle className="h-8 w-8 text-primary" />
              <CardTitle className="text-2xl">Limitations of AI Technology</CardTitle>
            </CardHeader>
            <CardContent className="pt-4">
              <p className="text-gray-700 mb-4">
                MediChat utilizes artificial intelligence technology which has inherent limitations:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>AI may not always understand the nuances of your specific situation</li>
                <li>AI cannot perform physical examinations or diagnostic tests</li>
                <li>AI may not be aware of the latest medical research or guidelines</li>
                <li>AI may not recognize rare conditions or unusual presentations of common conditions</li>
                <li>AI cannot account for all possible drug interactions or contraindications</li>
                <li>AI may have biases based on its training data</li>
              </ul>
              <p className="text-gray-700 mt-4">
                While we continuously work to improve our AI technology, these limitations are inherent to the nature of
                artificial intelligence and should be considered when using MediChat.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center gap-4 pb-2">
              <FileText className="h-8 w-8 text-primary" />
              <CardTitle className="text-2xl">Acknowledgment</CardTitle>
            </CardHeader>
            <CardContent className="pt-4">
              <p className="text-gray-700 mb-4">
                By using MediChat, you acknowledge that you have read and understood this medical disclaimer and agree
                to its terms. You accept that you are using the information provided by MediChat at your own risk and
                that neither MediChat nor its creators, operators, or affiliates will be liable for any decisions made
                or actions taken based on the information provided.
              </p>
              <p className="text-gray-700">If you do not agree with this disclaimer, please do not use MediChat.</p>
            </CardContent>
          </Card>

          <div className="mt-8 text-center">
            <Link href="/chat">
              <Button>Return to Chatbot</Button>
            </Link>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}

